### ISSUE TITLE
Issues detecting correct accounts

### ISSUE THREAD

**Issue by jabranham** [ledger/ledger-mode#101]
I'm having two different probably related issues:

1. ledger-magic-tab offers "assert commodity =='$'" when you define accounts like so at the top:

```
account assets:checking:
    assert commodity == "$"
```

So if you have (with | representing point):

```
2018-02-24
    ass|
```

and press TAB, you wind up with

```
2018-02-24
    assert commodity == "$"
```

2. When I do `M-x ledger-report`, and select a report that has `%(account)`, the resulting completions list to select an account includes non-accounts (for me, `; CSV: "Cleared", "01/06/2018", "restaurant-name"` is offered, for example).

Perhaps there should be a way to tell `ledger-mode` that the file in question uses e.g. `--pedantic` so that all the accounts are pre-declared at the top?

**Comment by DamienCassou** [comment]
Please check if https://github.com/ledger/ledger-mode/pull/124 fixes the issue.

**Comment by DamienCassou** [comment]
Is this issue fixed now?

**Comment by jabranham** [comment]
Yup! Thanks.
