### ISSUE TITLE
hledger support

### ISSUE THREAD

**Issue by gour** [ledger/ledger-mode#103]
Hello,

I am using hledger for generating reports about my journal, bu ledger-mode serves nicely for entering transactions...

However, I'd like to use it for reconciling accounts as well, but unfortunately, ledger cannot cope well with my journal file and it fails when/if I enable txn which contains balance assertion.

The strange thing is fails only with certain txns...in any case I'd like if ledger-mode could provide some specific support for hledger, so that one can configure invoking `hledger` executable when working with ledger file, doing reconciliation, reporting etc. ?

**Comment by purcell** [comment]
Can you provide an example of specific failing transactions please?

**Comment by gour** [comment]
My mistake - the problem was due to the differences how  (h)ledger handle balance assertions since in few asserions I do use [posting dates](http://hledger.org/journal.html#posting-dates) and therefore the amount was failing.

After I created `~/ledgerrc` with the `--permissive` option, everything is fine and ledger-mode can now be used for reconciling hledger journals as well. :smiley:

**Comment by purcell** [comment]
Great!
