### ISSUE TITLE
ledger-add-transaction sometimes does not suggest today's date

### ISSUE THREAD

**Issue by jthaman** [ledger/ledger-mode#108]
When I call `ledger-add-transaction`sometimes the incorrect date is suggested. This happens when I leave my computer on for many days. I think ledger-mode is just suggesting the date that Emacs was opened? Is this intended behavior?

By the way, thanks for this great software! It's a joy to use!

**Comment by jabranham** [comment]
`ledger-add-transaction` either uses the current date or the date of the last transaction you entered that way. So if you fire up ledger today and add a transaction (September 26th), then leave it open a few days and come back to it, C-c C-a will still suggest September 26th.

Closing this as not-a-bug.
