### ISSUE TITLE
Testing local changes to ledger-mode

### ISSUE THREAD

**Issue by delexi** [ledger/ledger-mode#115]
What is the recommended way to test changes I make in a local git checkout? Ideally I would like a script that builds ledger-mode as a package, starts a fresh emacs instance without configuration and installs said package.

Does something like this already exist for ledger-mode? If not, would this be a welcome contribution?

**Comment by jabranham** [comment]
Running `make test-batch` in the test directory should run most of ledger's tests, including checking that the files byte compile cleanly.

A script that installs ledger into a new Emacs instance is probably outside ledger-mode's scope. Perhaps cask or another tool provides something like that.
