### ISSUE TITLE
in org-babel ledger reports Error

### ISSUE THREAD

**Issue by wareslacker** [ledger/ledger-mode#120]
windows 10 1803 x86_64
emacs 26.1 x86_64
spacemacs develop 20180613 (open finance layer)
`(add-to-list 'org-babel-load-languages '(ledger . t))`

@purcell https://github.com/purcell/emacs.d also error

a test.org file:

```
* A simple test of ledger in an org file
The following are some entries and I have requested that ledger be run
to generate a balance on the accounts.  I could have asked for
a register or, in fact, anything at all the ledger can do through
command-line options.

#+begin_src ledger :cmdline bal :results value
2010/01/01 * Starting balance
  assets:bank:savings       £1300.00
  income:starting balances
2010/07/22 * Got paid
  assets:bank:chequing      £1000.00
  income:salary
2010/07/23 Rent
  expenses:rent              £500.00
  assets:bank:chequing
#+end_src

```

Typing C-c C-c or run ledger-report :

![default](https://user-images.githubusercontent.com/34468133/41325791-c0dea5ac-6eab-11e8-98d2-a685cf95659d.PNG)

**Comment by jueqingsizhe66** [comment]
which ledger
/cygdrive/c/Users/yzl/Desktop/ledger_3.1.1_win_bin/ledger

because cygwin use [cygpath](https://blog.csdn.net/hotdust/article/details/52344752) the change the command path, so what can we do it? I am trying to solve and have no idea!

**Comment by wareslacker** [comment]
![3](https://user-images.githubusercontent.com/34468133/41452548-06b619ca-70a5-11e8-82bc-ad9b4edfc755.PNG)
@jueqingsizhe66  I don't understand where the "/" come from.

**Comment by DriXse** [comment]
Other reference for this problem

 https://github.com/ledger/ledger/issues/555

**Comment by ngleb** [comment]
Ledger itself doesn't understand absolute paths in include statements (when built with msys2/mingw).
