### ISSUE TITLE
Can't shift month beyond current year

### ISSUE THREAD

**Issue by DamienCassou** [ledger/ledger-mode#128]
@jabranham [reported this](https://github.com/ledger/ledger-mode/pull/123#issuecomment-414169004):

> This doesn't seem to work if the next/previous month is in a different year, though, right? For me if I try to go from January 2018 to December 2017 --- it tries to change it from 2018-1 to 2018-0.

**Comment by DamienCassou** [comment]
I will work on it.

**Comment by jabranham** [comment]
This can be closed.
