### ISSUE TITLE
Generate invoices based on transactions

### ISSUE THREAD

**Issue by AvtechScientific** [ledger/ledger-mode#131]
It would be great to be able to generate a .pdf invoice based on a predefined template (in .org/.tex/etc formats; maybe utilizing org-mode exporter) for certain transaction (by default the current one, highlighted by cursor). A cool shortcut would be nice.

Thank you!

**Comment by purcell** [comment]
You would be able to build that functionality using the functions in `ledger-mode` which can parse transactions, but it is very tangential to `ledger-mode` and I don't think we'd ever add it here, sorry.
