### ISSUE TITLE
how to use with ledger on Windows?

### ISSUE THREAD

**Issue by dasboeh** [ledger/ledger-mode#140]
Hello.

On my working machine I've got to run Windows. But I want to use ledger with ledger-mode there, too.

I got the windows binaries from [here](https://github.com/AlexanderAA/ledger_binaries_windows). On cmd ledger seems to work.

How can I make ledger-mode to know the path to ledger.exe and use this?

Thansk for any help!

**Comment by excalamus** [comment]
What about using `ledger-binary-path`?  This could be an alternative to relying on the Windows PATH.

```
ledger-binary-path is a variable defined in ‘ledger-exec.el’.
Its value is "ledger"

  This variable may be risky if used as a file-local variable.

Documentation:
Path to the ledger executable.

You can customize this variable.

[back]

```

ledger-cli.org has a link to [a precompiled Windows binary](https://www.ledger-cli.org/download.html) (I believe this is the same source that you linked).  If you were to download that to, say, `C:\Users\Foo\Downloads\ledger.exe`, you could run the following with `M-:` or put it in your `init.el`:

```lisp
(setq ledger-binary-path "C:/Users/Foo/Downloads/ledger.exe")
```

**Comment by bcc32** [comment]
Setting `ledger-binary-path` should be a sufficient resolution here, closing.
