### ISSUE TITLE
ledger-mode adds trailing space when filling partial account names when using company-mode

### ISSUE THREAD

**Issue by ngleb** [ledger/ledger-mode#152]
I reported this usse to company-mode tracker in https://github.com/company-mode/company-mode/issues/861, but it was said there that this is the issue in ledger-mode. I'm using ledger-mode together with company mode. Issue started happening since company 0.9.9 stable release which had some bugfixing related to exit-function. According to the author of company, `company-capf` delegates to the major mode's completion function.

The problem is that in ledger I have account names like:
```
Assets:Savings:Account1
Assets:Cash
```
etc.

Since bugfixing was introduced in company, partial account names are inserted with trailing whitespace and isntead of "Assets:" I get "Assets: ".

If I disable company, then ledger completion works correctly, but I would prefer having company as well. Is it a known issue and could it be fixed in ledger-mode?

**Comment by jabranham** [comment]
I believe this shouldn't be an issue since we moved away from pcomplete in #174
