### ISSUE TITLE
Enhancement: ledger-account-rename

### ISSUE THREAD

**Issue by stettberger** [ledger/ledger-mode#154]
As my ledger usage changed over time I had to reorganize my account structure. While this can be done manually, I've written a account rename function. Don't know how this can fit into ledger-mode, but it's very useful for me.

https://gist.github.com/stettberger/aa991777b778290c9e5956a2820b91f4

**Comment by jabranham** [comment]
Thanks, very interesting. I've renamed a few accounts and just gone with the old trustworthy `M-%`. 

I'm not sure if we want this in ledger-mode, but perhaps we could put it in the manual under "Hacking Ledger Mode"? That seems like a good place to me for this sort of thing.
