### ISSUE TITLE
Disabling backend ledger-flymake because (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by plattfot** [ledger/ledger-mode#156]
Hi,
Found a bug in ledger's flymake backend when using emacs 26.1. Added a fix for it in #155.

To reproduce the error, just set `ledger-flymake-be-pedantic` and/or `ledger-flymake-be-explicit` to `nil` and enable the backend
```elisp
(add-hook 'ledger-mode-hook #'ledger-flymake-enable)
```
Open up an ledger file and then check the \*Flymake log\* buffer, it should say something like:
```
Warning [flymake ledger.dat]: Disabling backend ledger-flymake because (wrong-type-argument stringp nil)
```
Where ledger.dat is the ledger file.

**Comment by purcell** [comment]
Closing as a result of your fix in #155.
