### ISSUE TITLE
ledger-add-transaction: newly added transaction not fully visible

### ISSUE THREAD

**Issue by yurikhan** [ledger/ledger-mode#164]
To reproduce:

1. Start out with point at the end of buffer, and window scrolled so that point is at or near the last line of the window.
2. `C-c C-a`, date, payee, `RET`.

Observed: A new transaction is added, point is left at its start, the window is not scrolled so the new transaction is not fully visible.

Desired: The new transaction is fully visible if the window size permits it. Otherwise, the window is scrolled so that the new transaction’s first line is at the top, showing as much of the new transaction as possible.

What would be the best way to implement this to be consistent with all Emacs’s scrolling customization points (`scroll-conservatively` etc.)?

**Comment by jabranham** [comment]
We could add `ledger-after-add-transaction-hook` or something like that, but that might be overkill for this situation. I think this should be enough:

```lisp
  (advice-add 'ledger-add-transaction :after
              (lambda (_)
                "Recenter after adding transaction."
                (recenter)))
```

**Comment by yurikhan** [comment]
Posting my current workaround here for posterity:

```elisp
(advice-add 'ledger-add-transaction :after
            (lambda (_)
              (save-excursion
                (ledger-navigate-end-of-xact)
                (redisplay))))
```

I do not want to recenter after every added transaction. Rather, I want Emacs to behave as if I had typed the transaction manually — that is, keep point visible in the window as it progresses from the beginning to the end of the added transaction, respecting all the `scroll-{up,down}-aggressively` and `scroll-conservatively` settings. (For me, the latter is 101 so redisplay never recenters and only scrolls as little as possible to achieve point visibility.) I believe invoking redisplay at the end of the transaction and then letting Emacs invoke it again at the beginning is sufficient to achieve that goal.
