### ISSUE TITLE
Tab completion doesn't work on accounts

### ISSUE THREAD

**Issue by briansuhr** [ledger/ledger-mode#178]
I lost the ability to tab complete my accounts sometime between June 4 (the last time I ran ledger-mode) and now. 

I've tried fresh init.el and .ledger files with the same result. 

Running Emacs 26.2 on Windows 10.

**Comment by purcell** [comment]
Please can you provide steps to reproduce this? Note that the docs have changed to reflect the fact that `TAB` now works in a more standard Emacs way: you might like to set `tab-always-indent` to `'complete` if you were relying on `TAB` magic. (Note that the changes also allow complete-as-you-type systems like `company` to work seamless, where they didn't previously.)

**Comment by briansuhr** [comment]
Thanks, I didn't see that section in the docs. 

I was able to reproduce this on two machines, but your suggestion to include the hook resolved it. Of course, I've also _undone_ your suggestion on both machines and tab completion works as expected. ¯\\_(ツ)_/¯

**My steps were:**

1. Open an existing .ledger file
2. ```C-c C-a``` to create a new transaction
3. Begin typing an existing account name (e.g. ```Asset``` or ```Income:Intere```)
4. Press ```TAB```

**Expected Result**
Account name autocompletes to ```Assets:``` or ```Income:Interest Income```

**Actual Result**
Account name does not autocomplete and remains at ```Asset``` or ```Income:Intere```

**Comment by purcell** [comment]
> Thanks, I didn't see that section in the docs.

Yeah, it's very new, and it's not easy to bring changes like this to the attention of development-version users, sorry.



> Of course, I've also _undone_ your suggestion on both machines and tab completion works as expected.

Hmm. Maybe you're using `desktop-save-mode` and those settings were saved and restored with the buffers? Mysterious if not!

**Comment by russelldb** [comment]
As a comment, following your instructions above, tab complete is nothing like before. It is incredibly slow, and it completes multiple steps of the path in one go.

**Comment by jabranham** [comment]
@russelldb There was recently a fix for some slow completion. Can you make sure you're using the most recent version of ledger-mode?

If you are and it's still slow, can you report the results with `M-x profiler-start`, choose cpu, do some completion, then `M-x profiler-report`

**Comment by russelldb** [comment]
Thanks @jabranham, I did an update and it is noticeably faster.
