### ISSUE TITLE
Tab completion broken for payee

### ISSUE THREAD

**Issue by plattfot** [ledger/ledger-mode#181]
Hi,

updated to ledger-mode to `20190619.314` today. I use company-mode for the completion. After the update, completion stopped working entirely. Reading around on the issues and the docs I discovered I needed to add this to my config
```
(add-hook 'ledger-mode-hook
                 (lambda ()
                   (setq-local tab-always-indent 'complete)
                   (setq-local completion-ignore-case t)
                   (setq-local ledger-complete-in-steps t)))
```
Also found out why some of my accounts stopped working with completion awhile back (#141).

The issue I have now is that it includes the payee I'm currently typing in the list of suggested completions. So I cannot complete the payee I actually want, without navigating down in the completion list company gives me.
 
For example
```
2019/06/28 Foobar
    Expenses:Baz                               11.99 CAD
    Assets:Cash

2019/06/20 Foo|
``` 
Where `|` is my cursor. If I hit tab I get Foo and Foobar, if I continue typing it will suggest Foob and Foobar and so on. Expected behavior is to just get Foobar.

I see the same behavior if I disable company. Only then I cannot complete the payee at all. As it always matches against what I'm typing.

**Comment by bcc32** [comment]
I think that this was introduced by this pull request: https://github.com/ledger/ledger-mode/pull/174.  I wrote a comment to that effect.

**Comment by peti** [comment]
I have the same problem. `tab` completion of the payee field has been broken since the last update. :-(

**Comment by jabranham** [comment]
I submitted a fix for this, see #184.

I would've been faster to suggest a fix but no one tagged me here so I didn't know it was broken/annoying :-)

**Comment by purcell** [comment]
> I would've been faster to suggest a fix but no one tagged me here so I didn't know it was broken/annoying :-)

@jabranham You could always watch the repo to get notifications, at least until it becomes too annoying. :-)  You've been contributing quite a lot, so I might also suggest that @jwiegley consider adding you to the collaborators list. That way you could commit small fixes directly, and still file pull requests when you want feedback.

**Comment by jabranham** [comment]
@purcell fair enough. I've now done so. And John gave me access so I should be able to push commits directly now.

Thanks!

**Comment by purcell** [comment]
Cool, and thanks John!

**Comment by purcell** [comment]
Hey @abranham, I found that (after fixing the weird sorting order) the account completion suffered from the same problem, so I fixed it more generally, reverted your commit and added a test for this specific issue. See b4df0b62 if you're curious.

**Comment by plattfot** [comment]
Thank you for fixing this!
