### ISSUE TITLE
Recent changes broke completion of accounts with spaces

### ISSUE THREAD

**Issue by DamienCassou** [ledger/ledger-mode#185]
The following test was passing before but now fails. According to a quick bisect, e4e03eea7bff122173d9176bbb676518c0c0486c is the first bad commit.

```emacs
(ert-deftest ledger-complete/test-find-accounts-with-spaces-in-buffer ()
  (let ((ledger "*** Expenses
account Expenses:The Bakery
"))
    (with-temp-buffer
      (insert ledger)
      (should (equal
               (ledger-accounts-list-in-buffer)
               (list
                "Expenses:The Bakery"))))))
```

**Comment by purcell** [comment]
Thanks for the test case. This is fixed now. It was a mistake in the regexp which - surprisingly - didn't make the regexp syntactically invalid, due to the special meaning of `[` and `]` within `[]`.

**Comment by DamienCassou** [comment]
Steve Purcell <notifications@github.com> writes:
> Thanks for the test case.

Thank you so much for everything you do for the Emacs/Ledger
communities!!

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by purcell** [comment]
> Thank you so much for everything you do for the Emacs/Ledger communities!!

Cheers. The irony is that I'm not even working with `ledger` these days. Guess I'm just a compulsive fixer/tinkerer.
