### ISSUE TITLE
`ledger-accounts-list` gives incorrect accounts for separate files, breaking completion

### ISSUE THREAD

**Issue by cacology** [ledger/ledger-mode#187]
# Problem:

I have a `2019-journal.ledger` and a `2019-accounts.ledger` which merely has the account directives.   Completion stopped working in the journal file and it seems to be something about how `ledger-accounts-list` functions.

Calling `ledger-accounts-list` in `2019-journal.ledger` gives results that include the directives, i.e. `("Assets" "account Assets:Venmo" "account Assets:Wells Fargo Bank" "account Assets:Wells Fargo Bank:Checking" ... etc.`

Whereas, calling `ledger-accounts-list-in-buffer` in `2019-accounts.ledger` gives results without the directives, i.e. `("Assets" "Assets:Venmo" "Assets:Wells Fargo Bank" "Assets:Wells Fargo Bank:Checking" ... etc.`

# Possible solution:

I'm not sure why this is happening, but explicitly calling `ledger-mode` for the temp buffer made in `ledger-accounts-list` seems to solve my problem locally.  I'd make the pull request, but I'm not confident that this is the best solution:

```
(defun ledger-accounts-list ()
  "Return a list of all known account names as strings.
Looks in `ledger-accounts-file' if set, otherwise the current buffer."
  (if ledger-accounts-file
      (let ((f ledger-accounts-file))
        (with-temp-buffer
          (insert-file-contents f)
+++          (ledger-mode)
          (ledger-accounts-list-in-buffer)))
    (ledger-accounts-list-in-buffer)))
```

**Comment by purcell** [comment]
Thanks for the suggested fix: it indicated to me that the regexes we were using to detect account declarations worked differently according to the active syntax table. In this case, the meaning of `[[:space:]]` is different between `fundamental-mode` and `ledger-mode`: in `fundamental-mode`, it apparently matches newlines. A more direct fix has been committed.
