### ISSUE TITLE
TAB autocomplete doesn't work

### ISSUE THREAD

**Issue by ellingtonsantos** [ledger/ledger-mode#188]
TAB autocomplete doesn't work for accounts or payees since last update.

**Comment by jabranham** [comment]
How ledger handles completion has changed. Check the value of tab-always-indent. You probably want to change it to 'complete.

**Comment by ellingtonsantos** [comment]
Solved with:

(add-hook 'ledger-mode-hook
                 (lambda ()
                   (setq-local tab-always-indent 'complete)
                   (setq-local completion-ignore-case t)
                   (setq-local ledger-complete-in-steps t)))

As issue #181 suggests.

Thanks for your hint.
