### ISSUE TITLE
Request: Auto-indent second line of transactions

### ISSUE THREAD

**Issue by RyM21** [ledger/ledger-mode#19]
Thanks for this useful package.

After I enter the date and transaction name, I like to indent the remaining lines of a transaction (all but the first line). Currently, I have to do this manually, but I think every Ledger user does it. Could you add a setting to automatically indent each line of a transaction except the first? Thank you.

**Comment by purcell** [comment]
Do you mean that pressing TAB does not result in the right indentation? Or you want the second line to be auto-indented when you type return?

If the latter, that would be non-standard behaviour for Emacs modes: you can either get into the habit of using C-j (newline-and-indent) or rebind RET to newline-and-indent.

**Comment by RyM21** [comment]
Thanks, that's helpful. I meant the latter. However, for whatever reason, C-j doesn't work for me in Ledger mode; it places the point at the left margin (same as RET). This was the result of both `(electric-newline-and-maybe-indent)` and `(newline-and-indent)`.

**Comment by enderw88** [comment]
As Tim commented, auto indenting is non-standard for emacs major modes.

**Comment by purcell** [comment]
> As Tim commented, auto indenting is non-standard for emacs major modes.

Erm, presumably you meant Steve :-) But my point was that `newline-and-indent` should probably indent the second line of transactions, so I think this is a legitimate issue.

**Comment by joshd4** [comment]
`newline-and-indent` still doesn't seem to indent the second line of each transaction. Can this be reopened? It also seems to be an issue with indenting the line manually as well. Pressing tab selecting the second line will not correctly indent it.

**Comment by jabranham** [comment]
`newline-and-indent` does indent the second line of a transaction for me. `C-j` which is now `electric-newline-and-maybe-indent` does not, but that's how it is supposed to work I believe.

**Comment by joshd4** [comment]
Ah, that's my bad, I didn't see `C-j` was changed to `electric-newline-and-maybe-indent`. `newline-and-indent` does indeed work. Selecting the following region and pressing `TAB` which is bound to `indent-for-tab-command` does not indent the transaction properly, some issue with indenting ledger regions or is this also intended?

```ledger
2019/08/13 Test
this  8000 GBP
out
```

**Comment by jabranham** [comment]
Yes, that appears to be a bug. Can you please open a new issue?
