### ISSUE TITLE
please tag a release

### ISSUE THREAD

**Issue by bremner** [ledger/ledger-mode#194]
It looks like it's been 3 years and about 300 commits since the last release was tagged.

**Comment by jabranham** [comment]
I think this is because ledger-mode itself has never had a release. Those tags are from when ledger and ledger-mode lived in the same repo. Seems reasonable to me to cut a new release though.

**Comment by jabranham** [comment]
Who has the authority to make this happen? @purcell @enderw88 ?

**Comment by purcell** [comment]
Any of us can do it. I'm happy to add a new tag, but that's hardly a release process. :-)

**Comment by jabranham** [comment]
AFAIU ledger-mode hasn't ever had a release on its own so we probably don't have a release process. Seems like it's as good a time as any to come up with one. I've got no big ideas here, other than checking that the tests pass & there aren't compilation warnings. I suppose we could go through and appease checkdoc as well...

We also need to come up with a version number. `v3.1.1` is the last tag. I think probably the biggest change is the switch to how completion works, not sure if that merits `v4.0.0` or `v3.2.0`.

**Comment by purcell** [comment]
Yeah, just wondering about a changelog, because there *will* be people using the super-old version in MELPA Stable.

**Comment by jabranham** [comment]
Good idea. I can look through the log and put together some sort of a news
file.

**Comment by jabranham** [comment]
@purcell @enderw88 I think we're OK to tag `v4.0.0`, right?

**Comment by bitti** [comment]
Yeah, it's a shame that it's been so long. Is something else holding this off?

**Comment by purcell** [comment]
Done now. MELPA Stable should build v4.0.0 in the next few hours.
