### ISSUE TITLE
ledger-mode regressions

### ISSUE THREAD

**Issue by markokocic** [ledger/ledger-mode#198]
I am using the latest ledger-mode from melpa After update, I noticed the following regressions:

- TAB-Completion doesn't work any more - It used to work in account names and description. Previously I was able to cycle through suggestions by using TAB. Now it doesn't work at all.
- Automatic formatting of transaction after hitting RETURN key - When I press return after adding the account name and amount, the line get automatically reformatted, and a bunch of spaces added between account name and the amount.

Those two changes make using ledger-mode annoying to me. I tried to figure out how to bring back the old behaviour, but had no luck.

Note: Didn't try the git version. If it's fixed there, can you please release it to melpa?

The solution would be to either bring back the old default behaviour, or to provide info in documentation how to bring it back.

**Comment by jabranham** [comment]
Both of these changes are documented here: `(info "(ledger-mode) Adding Transactions")`
