### ISSUE TITLE
How is `ledger-minibuffer-history` assigned a value?

### ISSUE THREAD

**Issue by excalamus** [ledger/ledger-mode#199]
I'm working on learning the `ledger-mode` library and noticed that the `ledger-minibuffer-history` is defined and called, but doesn't seem to be *bound* at any point.

```
ahab@pequod:~/Projects/ledger-mode$ git pull
Already up-to-date.
ahab@pequod:~/Projects/ledger-mode$ ag ledger-minibuffer-history
ledger-report.el
147:(defvar ledger-minibuffer-history nil)

ledger-mode.el
115:                   collection nil nil nil 'ledger-minibuffer-history default))
120:               nil 'ledger-minibuffer-history default))

ledger-xact.el
178:                                      initial-string 'ledger-minibuffer-history)))

```

Is this something that needs to be implemented or is this cruft from a previous version?  Or, am I missing something altogether?

**Comment by purcell** [comment]
Just to nitpick, "bound" is the same as "defined", even if the initial bound value is nil. But I know what you mean. If you investigate the other `ag` hits above, and read the docstrings for the functions to which `'ledger-minibuffer-history` is passed, all will be revealed. :-)
