### ISSUE TITLE
Completion key-binding broken for Emacs 26.1 and ledger-mode 

### ISSUE THREAD

**Issue by badbob** [ledger/ledger-mode#213]
Looks like after switching from [pcomplete to completion-at-point](https://github.com/ledger/ledger-mode/pull/174) tab-completion completely broken for me.
My Emacs version:
```
GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.7)
 of 2019-04-11, modified by Debian
```
When I try to `C-h k + C-M-i` in ledger-mode I get:
```
C-M-i runs the command ispell-complete-word (found in
ledger-mode-map), which is an interactive autoloaded compiled Lisp
function in ‘ispell.el’.

It is bound to C-M-i, <menu-bar> <tools> <spell>
<ispell-complete-word>.
```
Only when I call manually `M-x competion-at-point`, I get `Completion` buffer with the appropriate completions.

**Comment by jabranham** [comment]
That's because ledger-mode is derived from text-mode, which binds it to ispell-complete-word. You can override this manually if you'd like `(define-key ledger-mode-map "\e\t" #'completion-at-point)`

**Comment by badbob** [comment]
@jabranham thanks a lot for your assistance! 
Here is full `.emacs` snippet:
```lisp
(eval-after-load 'ledger-mode 
   '(define-key ledger-mode-map [(tab)] #'completion-at-point))
```
What do you think, is it reasonable to override `text-mode` default binding in `ledger-mode-map` declaration inside [ledger-mode.el](https://github.com/ledger/ledger-mode/blob/master/ledger-mode.el#L237-L269) directly?

**Comment by purcell** [comment]
> What do you think, is it reasonable to override `text-mode` default binding in `ledger-mode-map` declaration inside [ledger-mode.el](https://github.com/ledger/ledger-mode/blob/master/ledger-mode.el#L237-L269) directly?

Your snippet overrides `TAB`, which wouldn't be desirable: it should do the right thing by default if you have `tab-always-indent` set to `'complete`, as per the info docs. Overriding `C-M-i` is probably a matter of user preference.

**Comment by badbob** [comment]
@purcell 
>  Overriding C-M-i is probably a matter of user preference.

That's exactly what I mean. As for me `C-M-i` should be declared in `ledger-mode.el` file.

**Comment by purcell** [comment]
Ah, right: I was missing that `C-M-i` is otherwise directly bound to `completion-at-point`, because I never use that binding myself. Yes, you're right, we should override it. Alternatively, it might make more sense to just derive `ledger-mode` from `fundamental-mode`, since `text-mode` seems an unusual choice.
