### ISSUE TITLE
ledger-subtract-commodity: Can’t subtract different commodities (10250000 "-0.0") from (2 "0.00")

### ISSUE THREAD

**Issue by LewWadoo** [ledger/ledger-mode#214]
ledger-mode or ledger takes an amount of say **0.00162473 BTC** as **162473 0.00**? How can I reconcile commodities of values less than 0.01? The scientific notation id doesn't undestand either, though it's probably should be a different issue.

**Comment by jladdjr** [comment]
I ran into this same issue. Here's my best sense of the issue:
* The error is saying that it found two different types of commodities --  in your case: "-0.0" and "0.00". I think the key difference is the sign. One is negative, the other positive. In my case I had `$` and `$-` as the two commodities.
* The error comes from ledger-mode itself as far as I can tell. The root issue seems to be with how it determines the commodity when dealing with 0 units of the commodity. In this case it somehow comes across a negative and positive version of the commodities.
* I think the issue may deal specifically with reconciling an account and clearing your _very first transaction_.
* While I had a very hard time attempting to debug the elisp code, my testing suggests that you can mark one transaction as being cleared and then the "0 commodity" issue no longer creeps up.

Sorry that there is so much speculation here. Debugging the ledger-mode code was very difficult and in the end I didn't find a good way of using `debug` or `edebug` to step through the code. (Emacs stepped into a compiled function and from that point on everything was opaque to me). I'll have to try to tackle that mountain another day.

Hope that helps!

**Comment by bcc32** [comment]
I think this was fixed by #361, but please reopen if you continue to experience this issue.
