### ISSUE TITLE
TAB is not completing account at point

### ISSUE THREAD

**Issue by noorul** [ledger/ledger-mode#216]
Once of the recent upgrade from melpa stable seems to have created this issue. I am using ledger mode 4.0.0 melpa stable. 

Describe key for TAB from ledger mode gives

It is bound to TAB.

(indent-for-tab-command &optional ARG)

Is there any recent change along this line?

**Comment by noorul** [comment]
Looks like I need to add the following 
`
(add-hook 'ledger-mode-hook
          (lambda ()
            (setq-local tab-always-indent 'complete)
            (setq-local completion-cycle-threshold t)
            (setq-local ledger-complete-in-steps t)))
`

**Comment by noorul** [comment]
But it looks like completion is taking more time than earlier

**Comment by purcell** [comment]
Thanks, closing as duplicate. If you have more info about A/B time comparisons to show what's getting slower, please feel free to open an issue about any significant slowdown.
