### ISSUE TITLE
tab completion not working

### ISSUE THREAD

**Issue by acarrico** [ledger/ledger-mode#219]
Tab completion isn't working at all in ledger-mode (NixOS's melpaPackages, I'll update this report with the version). I reverted to version ledger-mode 3.1.1 (NixOS's melpaStablePackages), and it works as expected.

**Comment by acarrico** [comment]
The broken version is listed as 20191008.1420

**Comment by acarrico** [comment]
I uninstalled the nixos versions of ledger-mode, and grabbed 20191226.2018 inside emacs. This version also fails to do tab completion. For now I'll run 3.1.1, which seems to work fine.

Thank you.

**Comment by purcell** [comment]
"Isn't working" is a bit vague. I'm assuming you just haven't configured the completion as directed in the manual and noted in the [changelog](https://github.com/ledger/ledger-mode/blob/master/NEWS.org).

**Comment by purcell** [comment]
(The completion mechanism used by `ledger-mode` switched from it's special-case always-on TAB behaviour to a behaviour that is more standard across all Emacs packages.)

**Comment by acarrico** [comment]
Thanks for the quick reply, I'll take a look at the change log you pointed me to.

**Comment by purcell** [comment]
Relevant (raw) manual section: https://github.com/ledger/ledger-mode/blob/5067e40805c40e83424d206584838ffa8c8117c7/doc/ledger-mode.texi#L290

**Comment by acarrico** [comment]
I'll close this report, and reopen if I have any trouble following that documentation. Hopefully this closed issue will point others in the right direction with the new version. I hadn't even realized my version had changed until I tried to figure out why my completion was broken. Thanks again.

**Comment by purcell** [comment]
Yep, there have been several other (now-closed) issues about this. I think I might make a short note in the README, but it still won't really avoid other people encountering this.

**Comment by purcell** [comment]
> I might make a short note in the README

Done. :-)
