### ISSUE TITLE
Windows 10: No such file or directory ledger

### ISSUE THREAD

**Issue by arqeco** [ledger/ledger-mode#230]
Hello,

I am trying ledger-mode on Windows 10. 
After installing ledger-mode from melpa I got this message when opening an .ledger file:

> File mode specification error: (file-missing Searching for program No such file or directory ledger)

How to specify the ledger program location?

**Comment by jabranham** [comment]
You can customize ledger-binary-path. I've just pushed a commit that should make this error message clearer to other users in the future.
