### ISSUE TITLE
Ledger-mode with org-mode headers and org-mode folding/display behaviour

### ISSUE THREAD

**Issue by wakatara** [ledger/ledger-mode#232]
I apologize if I've just been unable to find this in the documentation, while I've been able to find plenty of examples of babel use and org-mode, what I was actually hoping for the .emacs.d/init.el config string/option I would need to get org-mode headers (which I understand are seen as comments to get folding/revealing and working in my ledger files.

Right now, I've been using large comment blocks to denote sections of my file and organize it more sanely:

``` lisp
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Mar 2020 - CC
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
...
```

It would be much preferable, especially if I could have the folding/revealing behaviour of org-mode to be able to use headers such as 

``` org-mode
** Mar 2020 - CC
``` 

to organize and navigate my org files. The documentation seems to indicate this is available in ledger but I get a simple `* Mar 2020 - CC` in my ledger file when I do this rather than the nice heading I was expecting and which matches my org-mode configuration (sad panda).

Is this a matter of:

1. a config line in ledger to do this?
2. a change to my org-moe config to support this?
3. Not supported but a feature request I need to make?  =p 

I'd love some help here as I'm working on a blog post followup to a Ledger and Reckon post and  being able to navigate my ledger file with the same deftness as org-files would be a minor super-power.

This is my current `init.el` block for ledger:

``` elisp
(use-package ledger-mode
  :ensure t
  :defer t
  :init
  )
(add-to-list 'auto-mode-alist '("\\.ledger$" . ledger-mode))
```

and this is my current block surrounding which files are under org-mode (I was unsure if adding ledger files here would fix or explode things, but would love to add this hard to fund info into the blog post.

``` elisp

(use-package org
  :ensure org-plus-contrib
  :defer t
  :bind ("C-c d" . org-decrypt-entry)
  :config
  (require 'org-crypt)
  (org-crypt-use-before-save-magic)
  ;; more config setup
  :init
  (add-to-list 'auto-mode-alist '("\\.org$" . org-mode))
  (add-to-list 'auto-mode-alist '("\\.org_archive$" . org-mode))
  ;; continues on other directives for a *long* time... 
```

and thanks for ledger-mode, it has been loving how much time it has saved me.

**Comment by jabranham** [comment]
AFAIK we don't have any support for "folding" like org mode. You could probably hack something together based on outline-minor-mode if you wanted. Where did you see in the documentation that this was available?

**Comment by wakatara** [comment]
I ran across a note in the babel section which mentioned org-mode headings could be seen as comments so got all super excited I could organize my accounts hierarchically that way (as noted above, globbing large comment blocks in there is less than ideal.), wheres having things hierarchically organized 

```
* Mar 2020
** CDN Savings
** SIN Savings
** VIsa
** Credit Line
```

Is there any way that could be supported somehow as a feature request? I know other modes interact with org-mode, so just wondering if that's a "in ledger" or "in org-mode" request.

Btw, totally ❤️ the ledger-mode. Thank you for all your hard work on this. That, plus the Reckon gem has reduced my financial tracking overhead enormously (my banks csvxls exports are now the big problem. Lol.). 

Finished [a post on it yesterday. actually](https://daryl.wakatara.com/tracking-your-finances-with-reckon-and-ledger/).

Anyhow, org-mode headings support (since they are seen as comments anyway, so that it could integrate with the folding/hiding, would be *amazing*. Totally unsure how I would even go about implementing that at the moment as have not messed with creating or modifying a mode before (my lisp-fu is weak.).

Would origami possibly also be capable of supporting this if there was a magic hook in Ledger-mode? (though of course, the org-mode heading support would make the sections visually distinctive which would be amazing.).

thanks!

**Comment by jabranham** [comment]
You can do this with outline mode:

`M-x outline-minor-mode`

`C-c @ C-c` hides the entry at point

`C-c @ C-s` shows it

there are some other things you can do, see the Emacs manual for details `(info "(emacs) Outline Mode")`

**Comment by wakatara** [comment]
@jabranham 

Interesting. Very helpful since I had not thought about it his way. Thank you.

I've never used outline mode before, mostly because org-mode has folding and in Taskpaper mode I'd been using [origami](https://github.com/gregsexton/origami.el) to accomplish the same effect in `org-super-agenda`

I guess there are two things I'm looking for to make this work like thre rest of my workflow. Basically, if it quakes like a duck I am fine even if it is not "integrated".

1. *Fontification of comments with `*` bullets* organizationally so that it "looks" like org-mode (basically, so that I can see the headings and they stand out organizationally in the ledger file as if they were org-mode headings. (I have to look into this since it's not something I've done before and not sure how this works in emacs.). I am not sure how to make it do the funky thing with org-super-stars/org-bullets yet but that's chrome afaic
2. *Folding/revealing*. While outline minor mode does this (thanks!), it does nor work the same way as everything else I'm using, so it's friction. I noticed I can write an easy parser with origami to support this by the looks of things.

Will probably take a look at this during some covid-lockdown time since it would be super handy and I am trying to make it as easy as possible to organize and grok the ledger files (which get ridiculously long so more semantic structure built-in would help (me at least. YMMV.).

Sounds legit?

**Comment by jabranham** [comment]
1. You can solve with `font-lock-add-keywords` and `outline-font-lock-keywords`.
2. I'm not sure I understand. Can you be more specific or give an example?
3. You're looking for `outline-toggle-children`, I think.

Putting it all together, you'd want to do something like:

```elisp
(use-package ledger-mode
  :hook
  (ledger-mode . outline-minor-mode)
  :bind
  (:map ledger-mode-map
        ("TAB" . outline-toggle-children))
  :config
  (font-lock-add-keywords 'ledger-mode outline-font-lock-keywords))
```

**Comment by wakatara** [comment]
Hmmmm... I was trying to do this with the [outshine package from alphapapa](https://github.com/tj64/outshine) which is supposed to give you "org-mode" type fold/unfold effects with various file types. 

It has a dead basic. config, but am not sure what I'm missing to get it working with ledger-mode. This was the config (sorry to ask but a bit stumped at this point).

```
(use-package ledger-mode
  :ensure t
  :defer t
  :hook
  (ledger-mode . outshine-mode)
  :mode
  ("\\.ledger$" . ledger-mode)
  )
```
I did try to get the ledger-mode-map working with your commands, but it's unclear what makes outshine grok something is a comment in ledger mode (outshine is a "in top of" outline mode thing.).

Thoughts?

**Comment by wakatara** [comment]
(I'm realizing from googling a lot of people "want" this with ledger but could find nothing canonical telling you how to do it easily (or that seemed to work currently), so planning on posting it up with a nice searchable blog post on my site when I get it working. Twould be handy and I think it would actually help adoption of ledger, really... my only beef right now that I've got Reckon working with it and eliminating the drudgery of the maintenance work is being able to have it semantically segmented by month and account.   =]

**Comment by jabranham** [comment]
It looks like you can actually bind tab to `org-cycle` and it works just fine.

I'm not familiar with outshine. Is there something about outline that didn't meet your requirements?

**Comment by wakatara** [comment]
OMG, that works awesome with just outline mode (ignores custom org thingies I have like the ellipsis replacements, but works great and looks amazing. Thank you! - I have to admit to not having used outline-minor-mode before).

Just so it's written somewhere in case someone else comes looking for it, I'll just write the config I am using here. It's basicallt what you had, but it makes grooking the sections of a ledge file a million times nicer. 

``` elisp
(use-package ledger-mode
  :ensure t
  :defer t
  :hook
  (ledger-mode . outline-minor-mode)
  :bind
  (:map ledger-mode-map
        ("TAB" . org-cycle))
  :config
  (font-lock-add-keywords 'ledger-mode outline-font-lock-keywords)
  :mode
  ("\\.ledger$" . ledger-mode)
  )
```

Tis amazing what a difference a lot of these really small tweaks can make in terms of usability. Woo!  \o/
