### ISSUE TITLE
German date-formatting causes errors

### ISSUE THREAD

**Issue by mgmart** [ledger/ledger-mode#234]
When using German date formatting (19.04.2020), xact-entries (C-c TAB) lead to "Point is not after payee".
Sort does not work correctly either because the day seems to be regarded as the month.

**Comment by jabranham** [comment]
Here and elsewhere ledger-mode assumes that `/` or `-` are the characters separating years/months/days. 

We could solve the sorting issue by introducing a new variable and passing it to `sort-subr` when we call it from `ledger-sort-region`.

**Comment by mgmart** [comment]
I've solved the issue with ```ledger-fully-complete-xact``` so far (for me). 
I've  replaced any occurrences of ```[-/``` with ```[\.-/``` in ```ledger-regex.el```. With that ```ledger-fully-complete-xact``` works again for me. Don't know if that would cause any side effects. I'm fine with it for a couple of month now.

In the seldom cases I need to sort, it's sufficient for me to mark a month and use ```ledger-sort-region```.

> Here and elsewhere ledger-mode assumes that / or - are the characters separating years/months/days.

I've seen the issue regarding ```ledger-fully-complete-xact``` only for a year now. Before that ```ledger-mode``` worked with German date-formats out of the box (at least for me 😉). Not sure about sorting, though.

**Comment by jabranham** [comment]
This should be fixed by 021eff5f88bf6392d7b3e511593e07471eb7833d
