### ISSUE TITLE
Do not use `--date-format` for new transaction dates.

### ISSUE THREAD

**Issue by joostkremers** [ledger/ledger-mode#245]
When adding a new transaction with `ledger-add-transaction`, the user-provided date is converted to a string in `ledger-format-date` using the `--date-format` option in the user's `~/.ledgerrc` file if it's set.

However, `--date-format` is meant for printing dates, it is not the format that should be used for transaction dates in the ledger, that's what the option `--input-date-format` is for.

The current code also results in an error if `ledger-default-date-format` is not set to the same value as `--date-format`: `ledger-time-less-p` will complain that it cannot handle strings.

Some more details in [this Google Groups thread](https://groups.google.com/forum/#!topic/ledger-cli/dGbOTgZOh8g).

I don't know what the best solution to this issue is. I haven't looked at all the uses of `ledger-format-date` in the code to see if it should always use `--input-date-format` or if `--date-format` is correct in some cases. Though the fact that it uses `ledger-default-date-format` as a fallback suggests that `--input-date-format` is indeed what is intended.

BTW, wouldn't it make sense to initialize `ledger-default-date-format` to the `--input-date-format` option in `~/.ledgerrc`?

**Comment by jabranham** [comment]
Should be fixed, let me know if you continue to experience this issue

**Comment by joostkremers** [comment]
Thanks! Seems to be working fine.
