### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by jabranham** [ledger/ledger-mode#247]
@purcell CI seems to be failing to install ledger in the snapshot version. It's complaining that the-kenny isn't defined. He was removed a few weeks ago: https://github.com/NixOS/nixpkgs/pull/87353

I'm not very familiar with the github actions setup. Do we need to update nixpkgs somehow?

**Comment by purcell** [comment]
I just came across this myself: it will be resolved by https://github.com/ledger/ledger/pull/1919
