### ISSUE TITLE
Cannot create payee report if point is on an empty line.

### ISSUE THREAD

**Issue by joostkremers** [ledger/ledger-mode#249]
If I run `ledger-report` (`C-c C-o C-r`) and select a `payee` report when point is on an empty line between transactions, I get the following error:

    ledger-report-payee-format-specifier: Wrong type argument: stringp, nil

Turns out that `ledger-xact-payee` returns `nil` in this case, which `regexp-quote` in `ledger-report-payee-format-specifier` doesn't like.

Same thing happens when point is in a global comment.

**Comment by jabranham** [comment]
Thanks, should be fixed by 4b8b784a9feaa52c4cc207d5e8d7bfc5bf4fce68, let me know if you continue to have issues

**Comment by joostkremers** [comment]
It works now, thanks!
