### ISSUE TITLE
Add transaction not working correctly

### ISSUE THREAD

**Issue by fernandodrf** [ledger/ledger-mode#252]
When I used to add a transaction (pressing C-c C-a) it would drop to the mini-buffer and pre-populate it with transaction: YYYY/MM/, I could add additional data, hit enter and it would create the entry in the ledger file.

With the new changes, when I press C-c C-a, I get the calendar mini-window to select the date (just like you see with org-mode when you C-c C-s to schedule a TODO) if I either select a new date or just hit enter, the only thing it does is populate the ledger file with the date. 

Even if I disable the pop-up calendar as stated [here](https://github.com/ledger/ledger-mode/blob/master/NEWS.org) the only thing that is populated in the ledger file is the date. 

Ledger-mode would also scan for payees and accounts in the included files in the completion scan, which does not happens anymore.

Is it possible to get it to complete the transactions as in the previous versions of ledger-mode?

I have no special configuration for ledger-mode in my .emacs file.

I am using Manjaro linux, and GNU Emacs, Ledger, and Ledger-mode here are the version numbers:
- GNU Emacs 26.3
- Ledger 3.2.1-20200518
- Ledger-mode  20200524.1144

Thanks!

**Comment by sahhhm** [comment]
Having the same issues when using the latest published package on melpa. Haven't been able to find a workaround or more documentation on the change yet. Using the source code directly, I am able to replicate the issue off of the master branch; however, using the v4.0.0 (latest release) tag works as you initial describe above.

**Comment by sahhhm** [comment]
If you're like me and trying to work around this (and pulling your hair out!), make sure you're pulling from melpa-stable or tag v4.0.0 if referencing the source directly.

**Comment by jabranham** [comment]
You can get something approximating the old workflow by doing C-c C-a, choose the date, enter the payee (with completion), then C-c C-TAB to complete the transaction.

**Comment by calebmaxted** [comment]
I just updated ledger-mode and ran into this issue.

a93670e5cb8a362eefdeb941d2971c3ab29a51b9 completely breaks `ledger-add-transaction`.  As mentioned by @fernandodrf, this function now only inserts a date into the ledger buffer.  The functionality described in the last paragraph of `(info "(ledger-mode) Quick Add")` no longer exists.

> You can get something approximating the old workflow by doing C-c C-a, choose the date, enter the payee (with completion), then C-c C-TAB to complete the transaction.

What is the point of `ledger-add-transaction` then?  This is clearly a regression that breaks this function's sole purpose.  It's not called `ledger-add-date` (I'm not trying to be snarky, just trying to make the point.)
