### ISSUE TITLE
hledger, unknown flag

### ISSUE THREAD

**Issue by ricardoaiglesias** [ledger/ledger-mode#254]
## Context
I run emacs under the "doom-emacs" set of configurations, where I recently enabled ledger mode. The issue occurs when running `ledger-report` (`C-c C-o C-r`) on a file. I have both ledger and hledger installed.

I am running Ubuntu, 20.04LTS.

## What's the expected behavior?
When I run `hledger-report`, a report is shown. 

## What is the actual behavior?

When I run the command, I have the following string at the command prompt: 

` hledger -f /home/hyperion/Desktop/test.ledger reg Assets\:Bank\:Checking`

Upon entering it, I get the following screen in the `*Ledger Report*` buffer.

![hledger-emacs-1](https://user-images.githubusercontent.com/20539793/84444400-8c28a580-abf6-11ea-929b-7983e9bba4dd.png)

Running the `hledger` command in the terminal works fine, so I believe it is something to do with the flags passed in to the command. 

When changing from `hledger` to `ledger` on the command, it works fine, but I would like to know what flags are passed in (that are not shown in the `*Ledger Report*` buffer). 

## Extra Information
Below is a sample file I created to test the problem. 

[test.ledger](https://github.com/ledger/ledger-mode/files/4767632/test.txt)

**Comment by jabranham** [comment]
The `[[ledger-mode-flags]]` bit in some reports gets replaced with things. You can see what gets replaced in `ledger-report--compute-extra-args`. In this case, setting `ledger-report--cmd-needs-links-p` to nil will solve the issue.

BTW - I'm not sure if we support hledger officially or not

**Comment by ricardoaiglesias** [comment]
Thank you for the response! 
I was not able to find the variable in question through `C-h v`, but in any case, I did 
`(setq ledger-report--cmd-needs-links-p nil)`

and had a similar result. 

I was unaware that hledger was not supported, so will likely continue using ledger. 
`

**Comment by jabranham** [comment]
There's an old open issue about hledger: #56. So probably some people use ledger-mode just fine with it. 

Seems like your issue is solved though so I'm closing this ticket.

**Comment by purcell** [comment]
> I was unaware that hledger was not supported, so will likely continue using ledger.

I think it's just "less supported", and all our tests run against "ledger".
