### ISSUE TITLE
Feature Request: link to attached files

### ISSUE THREAD

**Issue by chrpinedo** [ledger/ledger-mode#256]
I think it would be interesting ledger-mode to support links to open documents.

In this git repository https://k.sfconservancy.org/NPO-Accounting/npo-ledger-cli/files/9f2a0cd1cc1bdeaec128e69a4b4c39687cb2c8c7/npo-ledger-cli-tutorial.md it is proposed to use tags in order to link documents such as invoices, receipts, purchase orders and other documents to transactions. For example:

```ledger
2012-02-05 Office Supply Galore - Online Order
        ;Receipt: accounts/documentation/org/receipts/2012-02-05_office-supply-galore.txt
    Expenses:Main Org:Office Supplies         $35.00
        ;Program: Main Org:Overhead
    Liabilities:Credit Card:Visa             $-35.00
```
It would be interesting to be able to mark "accounts/documentation/org/receipts/2012-02-05_office-supply-galore.txt" as a link and be able to open the document from ledger-mode of emacs.

**Comment by tbm** [comment]
I moved this issue to the ledger-mode repo.

**Comment by purcell** [comment]
I think you can already do this with something like Emacs' built-in `goto-addr` library or [org-link-minor-mode](https://github.com/seanohalpin/org-link-minor-mode). It's not something that needs to be added to `ledger-mode`. Note also that - even without any configuration - you can still run `M-x ffap` (find-file-at-point) with point on the path, and Emacs will open that file for you.
