### ISSUE TITLE
ledger-mode: report auto refresh, keep cursor position between refreshes (BZ#1089)

### ISSUE THREAD

**Issue by tbm** [ledger/ledger-mode#259]
Note: the issue was created automatically with bugzilla2github

Bugzilla bug ID: BZ#1089
From: Hans Erik van Elburg (@lowdef)
CC:   @tbm

**Comment by tbm** [comment]
I transferred this ticket from ledger to ledger-mode, but it sounds like it can be closed.

**Comment by lowdef** [comment]
Yes the fix was merged 5 years ago ;-) Can be closed.

**Comment by tbm** [comment]
Fixed in commit 5ff724c451fb09e73f055bcadc8b7ed2f79e0914
