### ISSUE TITLE
org-level highlighting for asterisk comments at flush left.

### ISSUE THREAD

**Issue by lawlist** [ledger/ledger-mode#272]
The following tweak to the variable `ledger-font-lock-keywords` might be of interest to anyone who uses `ledger-mode` and wants to organize his/her `ledger.dat` file with comment type flush-left asterisk headings -- with the same `org-level-...` colors used by `org-mode`.  [For those who may not already be aware, `outline-minor-mode` is useful for navigation ....]

**SCREENSHOT**:  https://lawlist.com/images/ledger_001.png

**CODE**:

    (progn
      (require 'ledger-mode)
      (require 'cl)
      (let ((pos (cl-position '("^[;#%|*].*$" quote ledger-font-comment-face) ledger-font-lock-keywords :test 'equal)))
        (when pos
          (push `(,(if org-fontify-whole-heading-line
                   "^\\(\\**\\)\\(\\* \\)\\(.*\n?\\)"
                   "^\\(\\**\\)\\(\\* \\)\\(.*\\)")
                 (1 (org-get-level-face 1))
                 (2 (org-get-level-face 2))
                 (3 (org-get-level-face 3)))
                 ledger-font-lock-keywords)
          (setcar (nthcdr (1+ pos) ledger-font-lock-keywords) '("^[;#%|].*$" quote ledger-font-comment-face)))))

**ledger.dat**:

    ; -*- ledger -*-

    = /^Income/
      (Liabilities:Tithe)                    0.12

    ;~ Monthly
    ;  Assets:Checking                     $500.00
    ;  Income:Salary

    ;~ Monthly
    ;   Expenses:Food  $100
    ;   Assets

    * Testing ONE

    ** Testing two a

    ** Testing two b

    *** Testing three a

    *** Testing three b

    **** Testing four a

    **** Testing four b

    ***** Testing five a

    ***** Testing five b

    ** Testing TWO

    * Testing THREE

    2010/12/01 * Checking balance
      Assets:Checking                   $1,000.00
      Equity:Opening Balances

    2010/12/20 * Organic Co-op
      Expenses:Food:Groceries             $ 37.50  ; [=2011/01/01]
      Expenses:Food:Groceries             $ 37.50  ; [=2011/02/01]
      Expenses:Food:Groceries             $ 37.50  ; [=2011/03/01]
      Expenses:Food:Groceries             $ 37.50  ; [=2011/04/01]
      Expenses:Food:Groceries             $ 37.50  ; [=2011/05/01]
      Expenses:Food:Groceries             $ 37.50  ; [=2011/06/01]
      Assets:Checking                   $ -225.00

**Comment by jabranham** [comment]
Thanks. This seems to be a pretty common want so I went ahead and added how to enable it to the "hacking ledger mode" section of the documentation.
