### ISSUE TITLE
ledger-toggle-current:  Infinity loop when certain conditions exist.

### ISSUE THREAD

**Issue by lawlist** [ledger/ledger-mode#274]
**Step 1**:  The last entry in the `ledger-mode` buffer is the following -- with `(point-max)` being immediately after the word "Checking"; i.e., no new line / no final new line -- to the immediate right of the letter "g" in the word `Checking` **==** `point-max/eobp`.  The buffer might be narrowed, or it might not be -- same result.

    2011/01/19 Grocery Store
      Expenses:Food:Groceries             $ 44.00 ; hastag: not block
      Assets:Checking

**Step 2**:  Place the cursor on the line with `2011/01/19 Grocery Store` and type `C-c C-c`

**Step 3**:  Observe the never ending infinity loop in process.  Newer versions of Emacs permit the user to exit with `C-g` a few times.  Older versions of Emacs require a force quit of the application.

Here is a *not* so eloquent workaround:

    (defun ledger-toggle-current (&optional style)
      "Toggle the current thing at point with optional STYLE."
      (interactive)
      (if (or ledger-clear-whole-transactions
              (eq 'transaction (ledger-thing-at-point)))
          (let ((point-a -1)
                (point-b 0))
            (save-excursion
              (forward-line)
              (goto-char (line-beginning-position))
              (while (and (not (= point-a point-b))
                          (not (eolp))
                          (save-excursion
                            (not (eq 'transaction (ledger-thing-at-point)))))
                (if (looking-at "\\s-+[*!]")
                    (ledger-toggle-current-posting style))
                (setq point-a (point))
                (forward-line)
                (goto-char (line-beginning-position))
                (setq point-b (point))))
            (ledger-toggle-current-transaction style))
        (ledger-toggle-current-posting style)))

**Comment by bcc32** [comment]
Thanks for reporting this!
