### ISSUE TITLE
Incorrect fontification of prices for commidities with spaces in their name

### ISSUE THREAD

**Issue by Alexander-Miller** [ledger/ledger-mode#292]
Ledger itself does support commodity names with spaces as numbers, the name just needs to be quoted. However that does not work for price directives, everything past the first space is seen as part of the price:

![price](https://user-images.githubusercontent.com/5951157/110680516-fd72a480-81d8-11eb-891a-8beac571a48d.png)

**Comment by doolio** [comment]
Can confirm I see the same behaviour.

**Comment by purcell** [comment]
This was a trivial fix, done
