### ISSUE TITLE
demo.ledger not found in repo

### ISSUE THREAD

**Issue by PhilippeCarphin** [ledger/ledger-mode#293]
The info in emacs says

> 1.3 Quick Demo
> ==============
> 
> Load the demo file ‘demo.ledger’ from the Ledger source ‘test/input’
> directory.  The ledger will be loaded and font highlighted.  At this
> point you could manually edit transactions and run Ledger from a
> convenient command line.

There is no directory test/input in the source (which I understood to mean this repo).

**Comment by purcell** [comment]
The "Ledger source 'test/input' directory" suggests to me the `ledger` repo, not this `ledger-mode` repo.

**Comment by purcell** [comment]
i.e. see https://github.com/ledger/ledger/blob/master/test/input/demo.ledger

**Comment by PhilippeCarphin** [comment]
Yes of course, I hadn't thought of that.  I heard of ledger and ledger-mode at the same time and I'm learning them together.

Thanks for the quick response.

**Comment by purcell** [comment]
No problem, enjoy your learning!
