### ISSUE TITLE
Suggestion: split ledger-mode-clean-buffer functionality

### ISSUE THREAD

**Issue by chrpinedo** [ledger/ledger-mode#301]
I would need to sort my ledger file with effective dates (asked in #268 by another user). However, since this is not ready yet, I can't run `ledger-mode-clean-buffer` function to indent and remove duplicates because it also sorts the file according to the date (not effective date).

Perhaps a function to clean indentation and remove duplicates would be suitable for users that want to sort the file by effective date or for users that do not want to sort its file at all.

**Comment by chrpinedo** [comment]
Just reading the section 2.8 of Ledger Manual I found the solution. I add the line `; Ledger-mode: Start sort` at the end of the file and thus I avoid to sort the file when I run `ledger-mode-clean-buffer`.

**Comment by purcell** [comment]
Great, glad you figured it out.
