### ISSUE TITLE
How to customize / switch pending and cleared faces?

### ISSUE THREAD

**Issue by markokocic** [ledger/ledger-mode#314]
In my personal workflow, I treat transactions with `*` as pending, and without as cleared, opposite from ledger defaults.

Is it possible to configure ledger-mode to invert font-faces used in the journal file? For example, to have cleared transactions displayed in red, and pending in blue?

**Comment by purcell** [comment]
I'm not aware that there's any built-in way to invert the meaning of pending and cleared, and I doubt it would be generally desirable, but you could presumably redefine the faces locally in your config.

**Comment by markokocic** [comment]
What worked for me is to put the following config into my init file:

```elisp
  (custom-set-faces
   '(ledger-font-payee-cleared-face ((t (:inherit error))))
   '(ledger-font-payee-uncleared-face ((t (:inherit success)))))
````
