### ISSUE TITLE
Native colors in report buffers in Emacs built from git nearly unreadable

### ISSUE THREAD

**Issue by jabranham** [ledger/ledger-mode#320]
Recently, Emacs' main branch gained support for more colors in shell buffers. Now account names in report buffers are displayed in a dark blue, which is nearly unreadable against a dark background. Has anyone else experienced this yet and if so how did you mitigate it?

Thanks!

**Comment by mngKd** [comment]
I got the same issue with the new pre-release of emacs 28 - 28.0.91.
Would be glad for any hints, where I could change that behavior.

**Comment by sdubinsky** [comment]
Did some testing, and it appears that these colors are coming from ledger itself, not from ledger-mode.  Looking at the ledger docs, there seems to be a limited number of colors available: https://www.ledger-cli.org/3.0/doc/ledger3.html#Colors.  I got this by setting `ledger-report-use-native-highlighting` to nil, and seeing the colors go away.

So I think you can choose another one of those, but it would be nice if ledger-mode let us customize them as well.

**Comment by marek-g** [comment]
Yes, it doesn't look like ledger-mode problem at all. What worked for me in Doom and Emacs 28 was adding the following lines to `config.el`:

```elisp
(custom-set-faces
 `(ansi-color-black ((t (:foreground ,(doom-color 'bg)))))
 `(ansi-color-red ((t (:foreground ,(doom-color 'red)))))
 `(ansi-color-green ((t (:foreground ,(doom-color 'green)))))
 `(ansi-color-yellow ((t (:foreground ,(doom-color 'yellow)))))
 `(ansi-color-blue ((t (:foreground ,(doom-color 'blue)))))
 `(ansi-color-magenta ((t (:foreground ,(doom-color 'magenta)))))
 `(ansi-color-cyan ((t (:foreground ,(doom-color 'cyan)))))
 `(ansi-color-gray ((t (:foreground ,(doom-color 'fg)))))
 `(ansi-color-bright-black ((t (:foreground ,(doom-color 'bg)))))
 `(ansi-color-bright-red ((t (:foreground ,(doom-color 'red)))))
 `(ansi-color-bright-green ((t (:foreground ,(doom-color 'green)))))
 `(ansi-color-bright-yellow ((t (:foreground ,(doom-color 'yellow)))))
 `(ansi-color-bright-blue ((t (:foreground ,(doom-color 'blue)))))
 `(ansi-color-bright-magenta ((t (:foreground ,(doom-color 'magenta)))))
 `(ansi-color-bright-cyan ((t (:foreground ,(doom-color 'cyan))))))
```

**Comment by heiwiper** [comment]
Just had the same issue this week after switching to Emacs 28.1, I don't know if that has to do anything with the problem but I still have my Emacs 27.1 installation and ledger-mode colors look consistent in that one.

Here's a comparison:
Emacs 27.1
![image](https://user-images.githubusercontent.com/12894695/173277098-6d066677-2da5-42e0-969d-beb26425e89a.png)

Emacs 28.1
![image](https://user-images.githubusercontent.com/12894695/173277129-af25f319-bcad-44b0-920b-d0698f7bfaa9.png)

The blue in the first picture is consistent with [moe-theme](https://github.com/kuanyui/moe-theme.el) which is the theme I use.

**Comment by purcell** [comment]
@heiwiper The solution is the same as above — the theme needs to be updated for Emacs 28.1. This isn't something specific to `ledger-mode`.

**Comment by helinwang** [comment]
Thanks. Is there a solution for regular (non-doom) emacs users?
