### ISSUE TITLE
Error on Emacs 28.1 when installing ledger-mode from Melpa

### ISSUE THREAD

**Issue by matthewspangler** [ledger/ledger-mode#331]
I am running Emacs version 28.1 on Manjaro Linux.

I install ledger-mode automatically from Melpa using the following lines in my emacs config:
`(use-package ledger-mode :ensure t)`

Emacs throws me the following error when starting it with `--debug-init`

> Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "ob-ledger")
>   require(ob-ledger)
>   org-babel-do-load-languages(org-babel-load-languages ((emacs-lisp . t) (haskell) (ledger . t) (python . t) (ruby . t)))
>   eval-buffer(#<buffer  *load*> nil "/home/nebulasurfer/.emacs.d/init.el" nil t)  ; Reading at buffer position 1060
>   load-with-code-conversion("/home/nebulasurfer/.emacs.d/init.el" "/home/nebulasurfer/.emacs.d/init.el" t t)
>   load("/home/nebulasurfer/.emacs.d/init" noerror nomessage)
>   startup--load-user-init-file(#f(compiled-function () #<bytecode 0x14cd1d40faa833aa>) #f(compiled-function () #<bytecode -0x1f3c686ddc0cdc35>) t)
>   command-line()
>   normal-top-level()

**Comment by purcell** [comment]
Okay, but `ob-ledger.el` isn't part of `ledger-mode`. It's part of `org-mode`. `ob-ledger` might simply not be included in the `org-mode` you have installed, e.g. the one bundled with your Emacs. Perhaps you need the `org-contrib` package or similar?

**Comment by matthewspangler** [comment]
You are right, per the release notes for the latest version (9.5) of org-mode. I didn't realize that. Thanks for your help!
