### ISSUE TITLE
Enabling flymake in ledger-mode

### ISSUE THREAD

**Issue by lcvass** [ledger/ledger-mode#346]
Enabling flymake-mode doesn't work as the ledger-flymake.el commentary suggests. What instead worked was creating a ledger-mode hook to call `ledger-flymake-enable`. Using Emacs 28.2 and latest ledger-mode from MELPA.

Additionally, is there any way to make flymake warn on --strict or --pedantic flags?

**Comment by doolio** [comment]
> Enabling flymake-mode doesn't work as the ledger-flymake.el commentary suggests. 

Can confirm.

**Comment by bcc32** [comment]
Thanks, I fixed the commentary to use your suggestion.

You can customize `ledger-flymake-be-pedantic` or `ledger-flymake-be-explicit` to make flymake pass `--pedantic` or `--explicit`, respectively.
