### ISSUE TITLE
Ledger Mode version 20170604.1757 Add Transaction not working correctly

### ISSUE THREAD

**Issue by dastagg** [ledger/ledger-mode#37]
When I press C-c C-a, in the past, the point would drop to the mini-buffer and pre-populate it with Transaction: YYYY/MM/, I would fill in the additional data, hit Return and it would create the entry in the ledger file.

Now when I press C-c C-a, I get the calendar mini-window to select the date (just like you see with org-mode when you C-c C-s to schedule a TODO or APPT) if I either select a new date or just hit Return(today's date), the only thing it does is populate the ledger file with the date. 

I moved that .emacs.d out of the way and installed spacemacs with the financial layer and C-c C-a works like it is supposed to.
    Spacemacs is using ledger-mode-2017042301748 and flycheck-ledger-20140605.1146.

So I moved the version below back to .emacs.d. Deleted ledger-mode-20170604.1757 and replaced it with ledger-mode-2017042301748 and it works like it is supposed to.

ArchLinux
Ledger 3.1.1-3 --- Although this is weird: Printout from yaourt -Ss ledger = aur/ledger 3.1.1-3 but Printout from ledger --version = Ledger 3.1.1-20160111.
ledger-mode-20170604.1757
flycheck-ledger-20140605.1146

This is my init.el file:
``` emacs-lisp
;;;  init.el --- Emacs startup file

;;; Commentary:

;; This file is the start up file for Emacs.

;;; Code:

(defconst custom-file (expand-file-name "custom.el" user-emacs-directory))
(when (not (file-exists-p custom-file))
  (write-region "" nil custom-file))
(setq custom-file custom-file)
(load custom-file)

;;; package setup
(require 'package)
(setq load-prefer-newer t
      package-enable-at-startup nil
      package-archives
      '(("gnu" . "https://elpa.gnu.org/packages/")
        ("org" . "http://orgmode.org/elpa/")
        ("melpa" . "https://melpa.org/packages/")))
(package-initialize)

;; Bootstrap "use-package"
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(setq use-package-verbose t
      use-package-always-ensure t)

(use-package ledger-mode
  :mode "\\.ledger\\'"
  :config
  (define-key ledger-mode-map (kbd "C-c c") 'ledger-mode-clean-buffer)
  (setq ledger-post-amount-alignment-at :decimal
        ledger-post-amount-alignment-column 49
        ledger-clear-whole-transactions t)
  (use-package flycheck-ledger))

;;; init.el ends here
```

**Comment by purcell** [comment]
Thanks. You're describing a recent change in behaviour, not necessarily an issue: date entry now uses the flexible `org-read-date`.

Is there a specific problem you're having?

**Comment by dastagg** [comment]
How do I get it to behave the same way it did before?

I type C-c C-a, it drops the point to the mini-buffer and fills in the year and month, I supply the date a name and a $ amount, hit return and it completes the transaction in my ledger file.

**Comment by purcell** [comment]
Aha! Right, I see what you mean. Yes, that's a regression. I'd love to keep the org date entry, though: how would it be to enter the date first, hit ENTER, and then be prompted again for the rest?

**Comment by purcell** [comment]
Okay, I think I've restored that previous behaviour - please let me know how you get on.

**Comment by dastagg** [comment]
I just installed the new version. It works as it did before. Thank you!

**Comment by purcell** [comment]
Cool, thanks for your patience. I'm trying to make a bunch of incremental tidy-ups and improvements, and tests don't cover all these use cases.
