### ISSUE TITLE
Ignore stderr?

### ISSUE THREAD

**Issue by cstm112** [ledger/ledger-mode#38]
Is it possible to have ledger-mode ignore any non stdout output from ledger? Due to a bug in (my compiled version of) boost, every execution of ledger binaries returns the following line via stderr, breaking ledger mode:

```
sys:1: RuntimeWarning: to-Python converter for boost::shared_ptr<ledger::commodity_pool_t> already registered; second conversion method ignored.
sys:1: RuntimeWarning: to-Python converter for boost::shared_ptr<ledger::(anonymous namespace)::collector_wrapper> already registered; second conversion method ignored.
```

**Comment by purcell** [comment]
I'd be very wary of patching ledger-mode to ignore this. Could you maybe write a local wrapper script that redirects `stderr`?

Alternative would be for us to redirect `stderr` to a `*ledger-errors*` buffer, which we would pop up when it grows. That might be a good idea, actually, if the alternative is obscure failures.

**Comment by cstm112** [comment]
Yep, that's what I currently do - i replaced ledger with a bash script that calls ledger and send sterr to /dev/null: `ledger  2> /dev/null
`
The problem is that ledger-mode fails silently if anything arrives via stderr - so I would really appreciate your second suggestion!

**Comment by purcell** [comment]
I have some code for this now, which allows us to more consistently handle when ledger fails: it redirects stderr to a separate buffer, which is then consistently displayed if the execution failed.

I'll check over it soon and commit it when I'm comfortable there are no unexpected side effects.

**Comment by purcell** [comment]
@cstm112 Please let me know how you get on with this change.

**Comment by cstm112** [comment]
perfect! thank you very much - it works!
