### ISSUE TITLE
Autocomplete does not work with Corfu

### ISSUE THREAD

**Issue by bradprob** [ledger/ledger-mode#394]
Hi, auto complete does not work for me in combination with Corfu. Corfu does work in C/C++ mode. Both Corfu and ledger-mode are activated in the ledger buffer.

**Comment by purcell** [comment]
Please can you be more specific than "does not work?" e.g. can you provide a little snippet to show what are you typing, and where you expect a completion to be available?

**Comment by purcell** [comment]
FWIW, I use corfu myself and just now tried completing an account name and it worked perfectly.

**Comment by bradprob** [comment]
I mean that no auto-completion happens. Completion seems not to work at all.
![20240114_13h17m01s_grim](https://github.com/ledger/ledger-mode/assets/30636071/101762e8-4769-480d-8b8b-9b361bf81fef)

Pressing C-c Tab in the screenshot results in "Foo:Foo"

**Comment by bradprob** [comment]
I toggled debugger on error (toggle-debug-on-error). Pressing C-c Tab, results in this message:
```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  ledger-fully-complete-xact()
  funcall-interactively(ledger-fully-complete-xact)
  command-execute(ledger-fully-complete-xact)
```

And this completion in the buffer:
![20240114_13h30m51s_grim](https://github.com/ledger/ledger-mode/assets/30636071/8314e197-59af-4572-a476-0b22eb649ee7)

**Comment by purcell** [comment]
Granted, that's not a great failure mode, but what's happening here is that you're misunderstanding the point of `ledger-fully-complete-xact`. It looks like the idea is that when you write "Some transaction" in the second transaction (ie. starting another transaction with the same _payee_) then hit `C-c TAB`, the prior transaction would be used to complete the first.

Probably you want is to trigger `completion-at-point` instead (which, in turn, would trigger `corfu` to use ledger's completion-at-point function). I don't think this bug report is anything to do with `corfu`, then — you're triggering a non-corfu function directly, so corfu isn't in the mix in your exampe.

**Comment by purcell** [comment]
I've never used `ledger-fully-complete-xact` myself btw.

For the benefit of other contributors here, [this](https://github.com/ledger/ledger-mode/blob/b1a8293461f528f73e15f0d4c603b0cb06486f68/ledger-complete.el#L355) is where the error comes from, because in this case `(ledger-thing-at-point)` returns `'posting`, so the block [here](https://github.com/ledger/ledger-mode/blob/b1a8293461f528f73e15f0d4c603b0cb06486f68/ledger-complete.el#L342) is never executed.

**Comment by bradprob** [comment]
Thanks for the reply! Indeed I misunderstood the function of ledger-fully-complete-xact.
