### ISSUE TITLE
Tab Completion does not register Virtual Accounts

### ISSUE THREAD

**Issue by rtjmay** [ledger/ledger-mode#4]
The tab completion function does not recognized virtual accounts that appear in the journal exclusively inside brackets.

Works:
Funds:Spending

Does not work:
(Funds:Spending)

Once a non-bracketed occurrence is registered, the tab completion works for future uses of that account--i.e. (Funds:Spen.... works correctly

**Comment by DamienCassou** [comment]
Please check if https://github.com/ledger/ledger-mode/pull/124 fixes the issue.

**Comment by rtjmay** [comment]
Yes, it does correct the issue -- virtual account transactions inside () or
[] are now correctly auto-completed.

Thanks.
