### ISSUE TITLE
ledger-reconcile-default-date-format setting is not respected

### ISSUE THREAD

**Issue by bcc32** [ledger/ledger-mode#408]
Setting `ledger-reconcile-default-date-format` to something different than
`ledger-default-date-format` seems to have no effect (the dates in reconcile
buffers still look like the latter).  It looks like the former variable is not
actually used anywhere.

**Comment by purcell** [comment]
Is there any good reason to support different date formats for different areas of functionality? Seems like everyone would be better off if we just used one, but perhaps I'm missing something.

**Comment by bcc32** [comment]
For reconciling, it might be handy to have ledger display the same date format as, e.g., your online banking website does.  Or perhaps it is overly verbose to display the year when reconciling a credit card statement from the last month?  I don't know why this variable was introduced in the first place, but that seems like a logical explanation to me—I've never seen a credit card statement that uses ISO8601 :)

Part of the confusion, at least for me, is that it's not obvious whether a given "date format" variable is used for output or input, or both.
