### ISSUE TITLE
Sorting in Reconcile Mode

### ISSUE THREAD

**Issue by kuerzn** [ledger/ledger-mode#430]
For a very important use case (clearing matching transactions/posting) it would be great to have the reconcile buffer sortet by absolute value of the amount. Is this possible? Or some way to provide a sorting function?

**Comment by bcc32** [comment]
The `ledger-reconcile-sort-key` option can be set to any expression (or comma-separated list of expressions) that ledger's `--sort` option would accept.  So, it can actually be set to `"abs(amount)"` to do the sorting that @kuerzn wants (I tested it and it seems to work fine).

I'll update the documentation of `ledger-reconcile-sort-key` to reflect this.
