### ISSUE TITLE
Eager macro-expansion failure

### ISSUE THREAD

**Issue by fmozturk** [ledger/ledger-mode#434]
https://github.com/ledger/ledger-mode/blob/964630f80e0e80dad83134a3660f56948390173a/ledger-report.el#L587

For GNU Emacs 29.4 (build 2, x86_64-w64-mingw32) of 2024-07-05, I got

Debugger entered--Lisp error: (error "Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2)")
  error("Eager macro-expansion failure: %S" (wrong-number-of-arguments (3 . 4) 2))
  internal-macroexpand-for-load((define-obsolete-function-alias 'ledger-report-kill #'ledger-report-quit) nil)
  eval-buffer()  ; Reading at buffer position 23862
  funcall-interactively(eval-buffer)
  command-execute(eval-buffer record)
  counsel-M-x-action("eval-buffer")
  ivy-call()
  ivy-read("M-x " [org-capture-goto-last-stored 0 org-element-paragraph-separate calendar-forward-week tramp-sudoedit-file-name-handler tramp-completion-handle-file-name-all-completions archive--file-desc-mode ivy-explorer org-indent-drawer Reduce\ To:\ to\ Cc: ivy-default-view-name c-electric-lt-gt pcomplete-stub japanese-hiragana-two-byte zmq org-export-before-processing-functions link-name uniquify-rename-buffer inactive 0 tramp-compat-string-equal-ignore-case raw-text-dos eshell-return-exits-minibuffer info--manual-names 0 viscii smie-config--guess-value search-emacs-glossary kmacro-pop-ring1 org-switch-to-buffer-other-window browse-url-gnome-moz-arguments vc-annotate tramp-sudoedit-handle-set-file-acl org-table-get-range 0 nswbuff ledger-regex-xact-line-group-code eshell--sep-terms int-file-name kmacro-p use-package-handler/:interpreter 0 filename-and-process slot-unbound org-get-org-file check-declare Parchment counsel--async-filter tramp-handle-make-auto-save-file-name puny-encode-digit ...] :predicate #f(compiled-function (sym) #<bytecode 0x1e429c71ee40836>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  command-execute(counsel-M-x)

**Comment by fmozturk** [comment]
Some how on melpa stable site, it is still same.

https://stable.melpa.org/packages/ledger-mode-4.0.0.tar

**Comment by purcell** [comment]
There's been no stable release of ledger-mode since Nov 2019, so it's overdue, but in the meantime you can try a snapshot version from regular MELPA.

**Comment by fmozturk** [comment]
I manually updated downloaded ledger-report.el file, there is no problem.

But someone who use melpa stable will encounter same problem.
