### ISSUE TITLE
Disable automatic fill-paragraph for long comments?

### ISSUE THREAD

**Issue by shimeike** [ledger/ledger-mode#435]
I typically use emacs with `visual-line-mode` activated, and I run `(fill-paragraph)` only as/if desired.

In my ledger transactions, I often utilise long in-line comments. However, these always automatically get broken at `fill-column` when using `ledger-mode`.

Is there a way to disable `ledger-mode`'s automatic `fill-paragraph` for inline comments? I have set `ledger-post-auto-align` to nil, but this seems to have no effect on the filling of comments. There do not appear to be any `ledger-post-` variables related to comments.

**Comment by bcc32** [comment]
I don't think ledger-mode does anything around this, and I don't observe this behavior in my Emacs.  Do you maybe have something enabling auto-fill-mode, for example on `text-mode-hook`?  `ledger-mode` derives from `text-mode`, not `prog-mode`, which may be surprising.

**Comment by shimeike** [comment]
Thanks for the reply - you are correct! My configuration issue!

`auto-fill-mode` was getting activated. For some reason I had missed this when checking `describe-mode`. And yes, you were also correct that it was getting activated due to a `text-mode` related configuration. Realising that I had explicitly disabled `auto-fill-mode` in `org-mode`, `TeX-mode`, and `message-mode` which are the text modes in which I normally work.
