### ISSUE TITLE
Syntax highlighting in org-mode block doesnot work.

### ISSUE THREAD

**Issue by ReichKV** [ledger/ledger-mode#52]
Syntax highlighting in a buffer with the ledger mode works perfectly. However in org-mode block  
#+begin_src ledger
2017/01/01 * Opening
    Assets:Bank               $1.00
    Equity:Opening Balances
#+end_src 
it doesnot work. 

I am not sure where is the issue. Is it the ledger mode or org-mode issue?

**Comment by DriXse** [comment]
You can try open the block with    C-c '

**Comment by jabranham** [comment]
You have to enable it by customizing `org-babel-load-languages`, see `(info "(org) Languages")`
