### ISSUE TITLE
Reconciliation mode doesn't work well with default accounts

### ISSUE THREAD

**Issue by shlevy** [ledger/ledger-mode#58]
`ledger-reconcile-visit` goes to the top of the ledger file and `ledger-reconcile-toggle` is a noop in a transaction where the account being reconciled is omitted as the default account.

**Comment by delexi** [comment]
Could you kindly provide a minimum ledger file and ledger report invocation that exhibit this behaviour? Additionally, what is your ledger mode version?

**Comment by shlevy** [comment]
```
account Credit Card
 alias cc
 default

2018/05/09 This Works
 Expenses  $100
 cc

2018/05/09 This Doesn't
 Expenses  $100

2018/05/09 This does though
 Expenses  $100
 cc
```

Using ledger-mode from ledger 3.1.1

I'm not sure what you mean by "ledger report invocation"... I run `ledger-reconcile` with `Credit Card` and see this behavior as I navigate the unreconciled transactions. When the cursor is on top of a transaction with the default account omitted, the full ledger buffer gets scrolled to the top. When I press SPC on that transaction, it doesn't modify anything.

**Comment by delexi** [comment]
> I'm not sure what you mean by "ledger report invocation"

I must have mixed up something there. I meant ledger-reconcile. The description you provided in your current answer was perfect! I could reproduce the issue on my end.

The reconcile functionality does not seem to have been written with default accounts in mind. Let's flesh out what ledger mode should do in this case.

1. What do you expect to happen, if you press space?
2. Where do you expect the cursor in the ledger buffer to land when navigating over a problematic transaction in the `*Reconcile*` buffer?

**Comment by shlevy** [comment]
I think the best behavior is to mark the entire transaction as pending on `ledger-reconcile-toggle` and have the cursor land at the top of the transaction in `ledger-reconcile-visit`

**Comment by delexi** [comment]
Ok, that is what I intuitively thought as well. I pushed a branch to my git repo that contains the change to make this happen. Would you mind giving that a try?

**Comment by shlevy** [comment]
That works perfectly, thank you!

**Comment by delexi** [comment]
I have been using my branch in my ledger mode usage and have not seen any problematic side effects of this change.
If it's possible, I would ask you to do the same and report any broken behaviour.
If nothing shows up, I will go ahead and make a pull request in one or two weeks.

**Comment by purcell** [comment]
Fix now merged - thanks @delexi!
