### ISSUE TITLE
'account' lines are not taken into account by TAB-completion

### ISSUE THREAD

**Issue by cpitclaudel** [ledger/ledger-mode#66]
In a file containing the following, pressing TAB doesn't complete `Exp` to `Expenses`.

```
account Expenses:Rent

2017/01/01 Landlord
  Exp
```

I don't expect this to be a very common use case, but sometimes it helps to list accounts first before starting a new ledger.

**Comment by simonmichael** [comment]
I would find this quite useful, eg when starting a new journal at the beginning of the year, or when starting out a new user with a fresh journal.

**Comment by purcell** [comment]
Yep, I have a fix to this which I haven't yet committed to `ledger-mode`, sorry.

**Comment by purcell** [comment]
(Background: I have a separate ledger file which lists all my valid accounts using `account` directives, so I want completion to look at used or declared accounts in my current file or - if overridden - that other "master" file.)

**Comment by purcell** [comment]
I committed a change in 45af4853 which should cause accounts declared with `account` directives to be included in completion results.

I'd personally like to overhaul the completion, because the current completion is built around `pcomplete`, which doesn't integrate at all with other completion mechanisms like `company` or the default `completion-at-point`...

**Comment by purcell** [comment]
Just pushing a few more tweaks now, in case anyone's rushing to try this.

**Comment by purcell** [comment]
Cool, so I think this is addressed now, and additionally you can make the accounts list for completion come from another file if you prefer, by setting `ledger-accounts-file`. Let me know if it does the trick for you, @cpitclaudel.

**Comment by cpitclaudel** [comment]
Yes, it works beautifuly!  Thanks a lot :)  

> I'd personally like to overhaul the completion, because the current completion is built around pcomplete, which doesn't integrate nicely with other completion mechanisms like company or the default completion-at-point...

It works pretty OK with company for me, at least :) But moving to completion-at-point might have the added benefit of allowing richer completion.  One thing that I don't like very much (but take this with a grain of salt, since I have <10h of ledger-mode experience) is that account completion works up to the next colon.  So for example if I have two account `Expenses:Food:Groceries" and `Expenses:Food:Dining out`, I'd like completion of `Exp` to offer both of the full account names, instead of having to invoke completion three times (one for `Expenses`, one for `Food`, and finally one for the last segment).  Even better, I'd love to be able to type `Exp:F:Gro`, or even `:Groceries` and have completion expand it to the full `Expenses:Food:Groceries`.

Should I open a feature request for this? It looks like what would be needed for the first request is a setting to bypass almost all of `ledger-accounts-tree` (btw, I think the docs of that function are not entirely correct: it claims to return all accounts, but it doesn't); for the second one, I'm not sure whether that's feasible in pcomplete.

**Comment by purcell** [comment]
Yeah, I also find `pcomplete` clunky for accounts due to the piecemeal completion. I guess the right way to do things would be to provide different regular completion functions that the user could choose to place in `completion-at-point-functions` instead of the current do-everything `pcomplete`-based function. Feel free to open a PR and reference this one. I'll close this specific issue now.

**Comment by cpitclaudel** [comment]
> Feel free to open a PR and reference this one.

I don't think I'll have time for that, but I'll be very happy if it does happen :)

**Comment by purcell** [comment]
LOL, sorry, I meant you could open an *issue*, not a PR. Must have been tired when I typed that. :-)
