### ISSUE TITLE
Missing newline at end of file confuses C-c C-q

### ISSUE THREAD

**Issue by cpitclaudel** [ledger/ledger-mode#67]
In a file containing just the following (no end-of-line), C-c C-q indents the last line by three spaces. That is, this:

```
2017-09-01 * Eversource
    Expenses:Utilities:Electricity            $14.33
    Assets:Home
```

becomes this:

```
2017-09-01 * Eversource
    Expenses:Utilities:Electricity            $14.33
       Assets:Home
```

Is this expected?

**Comment by delexi** [comment]
I tried to reproduce this with 457abb5962f2f9f40a052c139ace1c64bd6b01dc (current master) but was unsuccessful. Which version of ledger-mode did you use when this issue surfaced?

**Comment by cpitclaudel** [comment]
Indeed, it works on master :) Neat. I was using the then-current version on MELPA; not sure when it got fixed.
