### ISSUE TITLE
Is there a transpose transactions command?

### ISSUE THREAD

**Issue by cmal** [ledger/ledger-mode#8]
I've found a transpose transaction command is useful.
just like emacs' C-x C-t to transpose the last two lines, I want a ledger-mode transpose transactions command to transpose the last two records.
I'm new to emacs lisp. I wish I could do this job in the near future if this feature does not exist yet.
Any kind of help is welcome.
Thanks!

**Comment by enderw88** [comment]
Nothing like this exists now. Do you want to transpose postings or
transactions?

**Comment by cmal** [comment]
Sorry for confusing of the concepts.
e.g. I want to change

> 2012-03-11 * KFC(afternoon)
>     Expenses:Food                $20.00
>     Assets:Cash
>     (Budget:Food)               $-20.00
> 2012-03-11 * KFC(morning)
>     Expenses:Food                $20.00
>     Assets:Cash
>     (Budget:Food)               $-20.00

to 

> 2012-03-11 * KFC(morning)
>     Expenses:Food                $20.00
>     Assets:Cash
>     (Budget:Food)               $-20.00
> 2012-03-11 * KFC(afternoon)
>     Expenses:Food                $20.00
>     Assets:Cash
>     (Budget:Food)               $-20.00

Is this postings transposing?
Thanks!

**Comment by cmal** [comment]
Because every time I add a record to my ledger file, I look to my bank account's records and add the records one by one from the latest to the oldest till the record which I've already added to the ledger file. So I need to transpose the records just added to time order.

**Comment by enderw88** [comment]
Those are transactions. The individual account lines are postings.

**Comment by cmal** [comment]
Thanks. Can you help me with the method to distinguish the last two transactions before point? I would like to contribute a feature for that.

**Comment by enderw88** [comment]
It would make more sense to me to transpose the xacts before and after
point.

**Comment by cmal** [comment]
It sounds to be better, I think.
Ledger mode has a way to move point to before or after xacts, right? I don't have computer home to test that. :)

**Comment by yurikhan** [comment]
For me, `transpose-paragraphs` transposes transactions if they are separated by at least one blank line. It’s not bound to any key by default, though.

**Comment by cmal** [comment]
It works! Thank you for that.
