### ISSUE TITLE
Build system does not ignore site- and user-specific init files

### ISSUE THREAD

**Issue by scfc** [ledger/ledger-mode#94]
The build system currently does not run Emacs with `--no-site-file` and `--no-init-file`, potentially being influenced by local customizations (for better or worse).

For `ledger-mode` as part of `ledger`, I came up with a patch against `lisp/CMakeLists.txt` to call Emacs as `EMACSLOADPATH= ${EMACS_EXECUTABLE} […] -batch --no-init-file --no-site-file -f batch-byte-compile`.  This still applies (cf. https://github.com/scfc/ledger-mode/tree/ignore-init-files-when-byte-compiling), but would need to be adapted to include `test/Makefile`.

**Comment by purcell** [comment]
I think you'd just add those flags [here](https://github.com/scfc/ledger-mode/blob/ignore-init-files-when-byte-compiling/test/Makefile#L2), right?

**Comment by scfc** [comment]
@purcell Yes; I was hesitant because I did not understand `test-interactive`'s purpose, but (AFAICT) it does not interfere with that (I assume the warning about modified buffer `ledger-tests-26199BbX` is as designed?).  I'll post a pull request to see if Travis CI likes it.

**Comment by jabranham** [comment]
The Makefile includes `--quick` which should take care of this issue now.
